"""CICDGeneratorAgent — generates CI/CD configs and pre-commit hooks.

Covers §10.1.1-4:
- Pre-commit hook config (.pre-commit-config.yaml)
- GitHub Actions workflow
- GitLab CI template
- Branch protection gate suggestions
"""

from __future__ import annotations

from .base import (
    AgentGroup,
    AgentInput,
    AgentResult,
    AgentStatus,
    BaseAgent,
    Severity,
    make_finding,
    register,
)

_PRE_COMMIT_CONFIG = """# Auto-generated by Patchi — pre-commit hooks for instant feedback
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: detect-private-key

  - repo: local
    hooks:
      - id: patchi-sast
        name: Patchi fast SAST (Bandit + Semgrep)
        entry: python -m patchi.core.security.sast_gate
        language: system
        types: [python]
        pass_filenames: true
      - id: patchi-scan
        name: Patchi scan
        entry: patchi scan --staged
        language: system
        pass_filenames: false
"""

_GITHUB_ACTIONS_WORKFLOW = """# Auto-generated by Patchi — CI workflow with explicit SAST tools
name: Patchi Security
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install SAST tools
        run: pip install bandit semgrep

      - name: Bandit (SARIF)
        run: bandit -r . -f sarif -o bandit.sarif || true

      - name: Semgrep (SARIF)
        run: semgrep --sarif --config auto --output semgrep.sarif || true

      - name: Patchi consensus scan
        run: patchi scan --sarif .patchi/output.sarif || true

      - name: Upload Bandit SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif
          category: bandit

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep

      - name: Upload Patchi SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .patchi/output.sarif
          category: patchi

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
"""

_GITLAB_CI_TEMPLATE = """# Auto-generated by Patchi — GitLab CI template with explicit SAST tools
stages:
  - analyze

bandit:
  stage: analyze
  image: python:3.11-slim
  before_script:
    - pip install bandit
  script:
    - bandit -r . -f json -o bandit.json || true
  artifacts:
    reports:
      sast: bandit.json

semgrep:
  stage: analyze
  image: python:3.11-slim
  before_script:
    - pip install semgrep
  script:
    - semgrep --json --config auto --output semgrep.json || true
  artifacts:
    reports:
      sast: semgrep.json

patchi-scan:
  stage: analyze
  image: python:3.11-slim
  before_script:
    - pip install patchi
  script:
    - patchi scan
  artifacts:
    reports:
      code_quality: .patchi/output.sarif
"""


@register
class CICDGeneratorAgent(BaseAgent):
    """Generates CI/CD configs: pre-commit hooks, GitHub Actions, GitLab CI, branch protection."""

    group = AgentGroup.GUARD
    name = "CICDGeneratorAgent"
    description = "Generate .pre-commit-config.yaml, GitHub Actions, GitLab CI, and branch protection gates"

    def _run(self, inp: AgentInput, result: AgentResult) -> None:
        existing_precommit = inp.root / ".pre-commit-config.yaml"
        existing_github = inp.root / ".github" / "workflows" / "patchi-ci.yml"
        existing_gitlab = inp.root / ".gitlab-ci.yml"

        result.data["generated"] = []

        if not existing_precommit.exists():
            result.data["generated"].append(".pre-commit-config.yaml")
            result.findings.append(
                make_finding(
                    self.name,
                    "precommit_config",
                    Severity.INFO,
                    ".pre-commit-config.yaml",
                    "Generate pre-commit hook config for instant feedback",
                    detail=_PRE_COMMIT_CONFIG[:200],
                    suggestion="Run `patchi fix` to write this file",
                )
            )

        if not existing_github.exists():
            result.data["generated"].append(".github/workflows/patchi-ci.yml")
            result.findings.append(
                make_finding(
                    self.name,
                    "github_actions_workflow",
                    Severity.INFO,
                    ".github/workflows/patchi-ci.yml",
                    "Generate GitHub Actions workflow for CI",
                    detail=_GITHUB_ACTIONS_WORKFLOW[:200],
                    suggestion="Run `patchi fix` to write this file",
                )
            )

        if not existing_gitlab.exists():
            result.data["generated"].append(".gitlab-ci.yml")
            result.findings.append(
                make_finding(
                    self.name,
                    "gitlab_ci_template",
                    Severity.INFO,
                    ".gitlab-ci.yml",
                    "Generate GitLab CI template for CI",
                    detail=_GITLAB_CI_TEMPLATE[:200],
                    suggestion="Run `patchi fix` to write this file",
                )
            )

        # Branch protection gates check
        has_branch_protection = False
        for conf in ["CODEOWNERS", ".github/CODEOWNERS", "CODEOWNERS.txt"]:
            if (inp.root / conf).exists():
                has_branch_protection = True
                break

        if not has_branch_protection:
            result.findings.append(
                make_finding(
                    self.name,
                    "branch_protection",
                    Severity.MEDIUM,
                    "",
                    "No branch protection or CODEOWNERS detected",
                    detail="Set up branch protection rules requiring Patchi to pass before merge",
                    suggestion="Configure branch protection in GitHub/GitLab settings",
                )
            )

        result.data["templates"] = {
            "precommit": _PRE_COMMIT_CONFIG,
            "github_actions": _GITHUB_ACTIONS_WORKFLOW,
            "gitlab_ci": _GITLAB_CI_TEMPLATE,
        }

        result.files_scanned = 3
        if result.status == AgentStatus.RUNNING:
            result.status = AgentStatus.DONE
