"""`p docs` — Generate a project architecture document (Part 4 / Item 45).

Tier 1: pure rendering from Brain data, works with zero AI configured.
Tier 2: scoped AI narration (future, requires harness).

Output: a single Markdown file with table of contents, Mermaid diagrams,
tables, and cited evidence — designed to be portable context for new AI
conversations about the codebase.
"""

from __future__ import annotations

import logging
import time
from pathlib import Path
from typing import Any

_log = logging.getLogger(__name__)


def generate_docs(
    root: Path,
    *,
    brain_data: dict[str, Any] | None = None,
    ai_available: bool = False,
) -> str:
    """Generate a Markdown architecture document for the project.

    Tier 1 sections are always rendered.  Tier 2 sections are either
    rendered (if *ai_available*) or marked "unavailable — AI not configured".

    Returns the full Markdown string.
    """
    brain = brain_data or {}
    sections: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────
    project_name = _project_name(root, brain)
    sections.append(f"# {project_name} — Architecture\n")
    sections.append(f"_Generated by Patchi on {time.strftime('%Y-%m-%d')}_\n")
    sections.append("")

    # ── Table of Contents ─────────────────────────────────────────────────
    toc_items = [
        "1. [Project Overview](#project-overview)",
        "2. [Project Tree](#project-tree)",
        "3. [Routes](#routes)",
        "4. [Key Abstractions](#key-abstractions)",
        "5. [Dependency Graph](#dependency-graph)",
        "6. [Capabilities](#capabilities)",
        "7. [Functionality Checks](#functionality-checks)",
        "8. [AI Narration](#ai-narration)",
    ]
    sections.append("## Table of Contents\n")
    for item in toc_items:
        sections.append(f"- {item}")
    sections.append("")

    # ── Section 1: Project Overview ───────────────────────────────────────
    sections.append("## Project Overview\n")
    sections.append(_render_overview(root, brain))
    sections.append("")

    # ── Section 2: Project Tree ───────────────────────────────────────────
    sections.append("## Project Tree\n")
    sections.append(_render_tree(root, brain))
    sections.append("")

    # ── Section 3: Routes ─────────────────────────────────────────────────
    sections.append("## Routes\n")
    sections.append(_render_routes(brain))
    sections.append("")

    # ── Section 4: Key Abstractions ───────────────────────────────────────
    sections.append("## Key Abstractions\n")
    sections.append(_render_abstractions(brain))
    sections.append("")

    # ── Section 5: Dependency Graph (Mermaid) ─────────────────────────────
    sections.append("## Dependency Graph\n")
    sections.append(_render_dependency_diagram(brain))
    sections.append("")

    # ── Section 6: Capabilities ───────────────────────────────────────────
    sections.append("## Capabilities\n")
    sections.append(_render_capabilities(root, brain))
    sections.append("")

    # ── Section 7: Functionality Checks ───────────────────────────────────
    sections.append("## Functionality Checks\n")
    sections.append(_render_functionality_checks(brain))
    sections.append("")

    # ── Section 8: AI Narration (Tier 2) ──────────────────────────────────
    sections.append("## AI Narration\n")
    if ai_available:
        sections.append("_Tier 2 narration would appear here with AI configured._\n")
    else:
        sections.append(
            "_Unavailable — AI not configured. Configure an AI provider "
            "with `p key add` to enable scoped narration for abstractions "
            "and user flows._\n"
        )
    sections.append("")

    return "\n".join(sections)


# ── Section renderers ────────────────────────────────────────────────────────


def _project_name(root: Path, brain: dict) -> str:
    """Derive project name from manifest or directory name."""
    purpose = brain.get("project_purpose", "")
    if purpose and "—" in purpose:
        return purpose.split("—")[0].strip()
    if purpose and ":" in purpose:
        return purpose.split(":")[0].strip()
    return root.name


def _render_overview(root: Path, brain: dict) -> str:
    lines: list[str] = []
    purpose = brain.get("project_purpose", "Project purpose not yet determined.")
    lines.append(f"**Purpose:** {purpose}\n")

    stats = brain.get("stats", {})
    if stats:
        parts = []
        if stats.get("file_count"):
            parts.append(f"{stats['file_count']} files")
        if stats.get("route_count"):
            parts.append(f"{stats['route_count']} routes")
        if stats.get("function_count"):
            parts.append(f"{stats['function_count']} functions")
        if stats.get("class_count"):
            parts.append(f"{stats['class_count']} classes")
        if parts:
            lines.append(f"**Size:** {', '.join(parts)}\n")

    stack = brain.get("stack", {})
    if stack:
        langs = stack.get("languages", [])
        fws = stack.get("frameworks", [])
        if langs:
            lines.append(f"**Languages:** {', '.join(langs)}\n")
        if fws:
            lines.append(f"**Frameworks:** {', '.join(fws)}\n")

    return "\n".join(lines)


def _render_tree(root: Path, brain: dict) -> str:
    """Render a simplified project tree from file discovery data."""
    file_infos = brain.get("file_infos", [])
    if not file_infos:
        return "_No file discovery data available._\n"

    # Group by top-level directory.
    from collections import defaultdict

    dirs: dict[str, list[str]] = defaultdict(list)
    for fi in file_infos:
        path = getattr(fi, "path", str(fi))
        parts = Path(path).parts
        if len(parts) > 1:
            dirs[parts[0]].append(path)
        else:
            dirs["."].append(path)

    lines = ["```"]
    for d in sorted(dirs.keys()):
        files = sorted(dirs[d])
        lines.append(f"{d}/")
        for f in files[:20]:  # Cap per dir.
            lines.append(f"  {Path(f).name}")
        if len(files) > 20:
            lines.append(f"  ... and {len(files) - 20} more")
    lines.append("```")
    return "\n".join(lines)


def _render_routes(brain: dict) -> str:
    routes = brain.get("routes", [])
    if not routes:
        return "_No routes detected._\n"

    lines = ["| Method | Path | Handler | Auth |"]
    lines.append("|--------|------|---------|------|")
    for r in routes[:50]:
        method = getattr(r, "method", "") if hasattr(r, "method") else r.get("method", "")
        path = getattr(r, "path", "") if hasattr(r, "path") else r.get("path", "")
        handler = getattr(r, "handler", "") if hasattr(r, "handler") else r.get("handler", "")
        auth = getattr(r, "auth_required", None) if hasattr(r, "auth_required") else r.get("auth_required")
        auth_str = "Yes" if auth else ("No" if auth is not None else "?")
        lines.append(f"| {method} | `{path}` | `{handler}` | {auth_str} |")

    if len(routes) > 50:
        lines.append(f"\n_Showing 50 of {len(routes)} routes._")

    return "\n".join(lines)


def _render_abstractions(brain: dict) -> str:
    """Render key abstractions — highest fan-in/fan-out from symbol graph."""
    symbols = brain.get("symbols", [])
    if not symbols:
        return "_No symbol graph data available._\n"

    # Compute fan-in from edges.
    edges = brain.get("symbol_edges", [])
    fan_in: dict[int, int] = {}
    for e in edges:
        target = e.get("target", 0) if isinstance(e, dict) else getattr(e, "target_id", 0)
        fan_in[target] = fan_in.get(target, 0) + 1

    # Rank by fan-in.
    ranked = sorted(symbols, key=lambda s: fan_in.get(s.get("id", 0) if isinstance(s, dict) else getattr(s, "id", 0), 0), reverse=True)

    lines = ["| Symbol | Kind | File | Fan-in |"]
    lines.append("|--------|------|------|--------|")
    for s in ranked[:20]:
        name = s.get("name", "") if isinstance(s, dict) else getattr(s, "name", "")
        kind = s.get("kind", "") if isinstance(s, dict) else getattr(s, "kind", "")
        f = s.get("file", "") if isinstance(s, dict) else getattr(s, "file", "")
        sid = s.get("id", 0) if isinstance(s, dict) else getattr(s, "id", 0)
        fi = fan_in.get(sid, 0)
        lines.append(f"| `{name}` | {kind} | `{f}` | {fi} |")

    return "\n".join(lines)


def _render_dependency_diagram(brain: dict) -> str:
    """Render a Mermaid dependency diagram from import graph data."""
    import_graph = brain.get("import_graph")
    if not import_graph:
        return "_No import graph data available._\n"

    try:
        from patchi.core.brain.mermaid import dependency_diagram

        return f"```mermaid\n{dependency_diagram(import_graph)}\n```"
    except Exception as e:
        _log.debug("Mermaid generation failed: %s", e)
        return "_Diagram generation unavailable._\n"


def _render_capabilities(root: Path, brain: dict) -> str:
    """Render the code-derived capability inventory."""
    try:
        from patchi.core.brain.capability_inventory import build_inventory

        inv = build_inventory(
            root,
            file_infos=brain.get("file_infos"),
            routes=brain.get("routes"),
        )
        if inv.total == 0:
            return "_No capabilities discovered from code._\n"

        lines = [f"_{inv.summary()}_\n"]

        # Route capabilities.
        if inv.routes:
            lines.append("### Routes\n")
            for e in inv.routes[:30]:
                lines.append(f"- `{e.name}` — {e.description}")
            lines.append("")

        # Agent capabilities.
        if inv.agents:
            lines.append("### Agents\n")
            by_group: dict[str, list] = {}
            for e in inv.agents:
                g = e.meta.get("group", "other")
                by_group.setdefault(g, []).append(e)
            for group, agents in sorted(by_group.items()):
                lines.append(f"**{group}:** {', '.join(a.name for a in agents[:10])}")
                if len(agents) > 10:
                    lines.append(f"  _...and {len(agents) - 10} more_")
            lines.append("")

        return "\n".join(lines)
    except Exception as e:
        _log.debug("Capability inventory failed: %s", e)
        return "_Capability inventory unavailable._\n"


def _render_functionality_checks(brain: dict) -> str:
    """Render critical flows from the contract."""
    contract = brain.get("contract", {})
    flows = contract.get("flows", [])
    if not flows:
        return "_No contract flows detected._\n"

    critical = [f for f in flows if f.get("critical", False)]
    if not critical:
        return f"_{len(flows)} flows detected, none marked critical._\n"

    lines = [f"_{len(critical)} critical flows:_\n"]
    for f in critical[:20]:
        name = f.get("name", "?")
        desc = f.get("description", "")
        routes = f.get("routes", [])
        route_str = ", ".join(f"`{r}`" for r in routes[:3]) if routes else "no routes"
        lines.append(f"- **{name}**: {desc} ({route_str})")

    return "\n".join(lines)
