"""`p governance impact --out` — the symbol blast-radius answer as a PR-ready
markdown report.

Contract (mirrors the reason_cmd --out tests): the file is valid pastable
markdown with a provenance stamp, the 15-file display cap is stated honestly
(not silently dropped), stdout never duplicates the report, --out and --json
are mutually exclusive with exit 2, and a zero-reference symbol still writes
a real report that says so.
"""

from __future__ import annotations

import json

import pytest

from patchi.cli.commands.governance_cmd import _cmd_impact, _impact_markdown


@pytest.fixture()
def seeded(tmp_path, monkeypatch):
    """Three files reference the symbol; result claims 18 refs so the
    15-row display truncation is exercised."""
    import patchi.core.security.blast_radius as br

    refs = [f"src/ref_{i:02d}.py" for i in range(18)]
    monkeypatch.setattr(
        br, "patchi_blast_radius", lambda symbol, root: {
            "symbol": symbol,
            "reference_count": len(refs),
            "referencing_files": refs,
            "blast_level": "high",
        }
    )
    return tmp_path


@pytest.fixture()
def empty(tmp_path, monkeypatch):
    """A symbol nobody references."""
    import patchi.core.security.blast_radius as br

    monkeypatch.setattr(
        br, "patchi_blast_radius", lambda symbol, root: {
            "symbol": symbol,
            "reference_count": 0,
            "referencing_files": [],
            "blast_level": "low",
        }
    )
    return tmp_path


def test_out_writes_pr_ready_markdown(seeded):
    out = seeded / "blast.md"
    rc = _cmd_impact(seeded, "mySymbol", json_output=False, out=out)
    assert rc == 0
    text = out.read_text(encoding="utf-8")
    assert text.startswith("# Blast radius — `mySymbol`")
    assert "18 reference(s)" in text and "high" in text
    assert "| # | Referencing file |" in text
    assert "`src/ref_00.py`" in text
    assert "Generated by `p governance impact --out`" in text  # provenance stamp


def test_out_states_truncation_honestly(seeded):
    """18 references but 15 rows: the report must say what it left out."""
    out = seeded / "blast.md"
    _cmd_impact(seeded, "mySymbol", json_output=False, out=out)
    text = out.read_text(encoding="utf-8")
    assert "`src/ref_14.py`" in text  # row 15 shown
    assert "`src/ref_15.py`" not in text  # row 16 not shown
    assert "3 more reference(s) not listed" in text


def test_stdout_never_duplicates_the_report(seeded, capsys):
    out = seeded / "blast.md"
    _cmd_impact(seeded, "mySymbol", json_output=False, out=out)
    captured = capsys.readouterr()
    assert "ref_00" not in captured.out  # table went to the file, not stdout
    assert str(out) in captured.out  # but the pointer is on stdout


def test_zero_references_still_writes_a_real_report(empty):
    """Honesty: no data is content ('no referencing files'), never an empty
    or missing file."""
    out = empty / "blast.md"
    rc = _cmd_impact(empty, "ghost", json_output=False, out=out)
    assert rc == 0
    text = out.read_text(encoding="utf-8")
    assert "0 reference(s)" in text
    assert "No referencing files found" in text


def test_out_and_json_are_mutually_exclusive(seeded, capsys):
    rc = _cmd_impact(seeded, "mySymbol", json_output=True, out=seeded / "blast.md")
    assert rc == 2
    out = capsys.readouterr().out
    assert "--out" in out and "--json" in out
    assert not (seeded / "blast.md").exists()


def test_json_mode_is_untouched_by_out_support(seeded, capsys):
    """The pre-existing machine contract stays byte-pure JSON on stdout."""
    import contextlib
    import io

    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        rc = _cmd_impact(seeded, "mySymbol", json_output=True, out=None)
    assert rc == 0
    doc = json.loads(buf.getvalue())
    assert doc["reference_count"] == 18
    assert doc["blast_level"] == "high"


def test_markdown_shapes_all_blast_levels():
    """Direct renderer check: low/zero through the truncation path."""
    assert "No referencing files found" in _impact_markdown(
        {"symbol": "x", "reference_count": 0, "referencing_files": [], "blast_level": "low"}
    )
    few = _impact_markdown(
        {
            "symbol": "x",
            "reference_count": 2,
            "referencing_files": ["a.py", "b.py"],
            "blast_level": "low",
        }
    )
    assert "`a.py`" in few and "not listed" not in few  # nothing truncated


def test_registry_declares_governance_impact_out_flag():
    """The flag parses on the real parser and stays exclusive of the
    positional default — catches registry/flag drift."""
    from patchi.cli.main import _build_parser

    parser = _build_parser()
    args = parser.parse_args(["governance", "impact", "sym", "--out", "r.md"])
    assert str(args.out) == "r.md"
    args_json = parser.parse_args(["governance", "impact", "sym", "--json"])
    assert args_json.out is None
