"""`p why --out` / `p impact --out` — markdown reports written for PRs/docs.

The contract: the file is valid pastable markdown (fenced mermaid for the
mermaid path), stdout never duplicates the report, and every failure mode
honestly reports on stderr with a non-zero exit instead of silently writing
a wrong or empty file.
"""

import pytest

from patchi.cli.commands.reason_cmd import run_impact, run_why


@pytest.fixture()
def graph_root(tmp_path, monkeypatch):
    """A project root whose cached brain memory holds a small import graph:

        caller_a.py  -> core.py
        caller_b.py  -> core.py
        core.py      -> helper.py, other.py
    """
    import patchi.core.memory as mem

    data = {
        "import_graph": {
            "nodes": ["caller_a.py", "caller_b.py", "core.py", "helper.py", "other.py"],
            "edges": {
                "caller_a.py": ["core.py"],
                "caller_b.py": ["core.py"],
                "core.py": ["helper.py", "other.py"],
            },
        }
    }
    monkeypatch.setattr(mem, "get_brain", lambda root=None, *a, **k: data)
    return tmp_path


@pytest.fixture()
def no_brain(tmp_path, monkeypatch):
    """A project root with NO layered brain (engine.why returns an error)."""
    import patchi.core.memory as mem

    monkeypatch.setattr(mem, "get_brain", lambda root=None, *a, **k: {})
    return tmp_path


# ── p why --out ──────────────────────────────────────────────────────────────


def test_why_mermaid_out_writes_fenced_report(graph_root):
    out = graph_root / "report.md"
    run_why("core.py", root=graph_root, mermaid=True, out=out)
    text = out.read_text(encoding="utf-8")
    assert text.count("```mermaid") == 2  # dependents walk + call-flow walk
    assert "caller_a" in text or "caller_b" in text  # dependents walk names an importer
    assert "helper" in text or "other" in text  # call-flow walk names an import


def test_why_mermaid_out_does_not_duplicate_on_stdout(graph_root, capsys):
    out = graph_root / "report.md"
    run_why("core.py", root=graph_root, mermaid=True, out=out)
    stdout = capsys.readouterr().out
    assert "```mermaid" not in stdout  # diagram only in the file, not also stdout
    assert out.name in stdout  # but stdout says where the report went


def test_why_out_without_brain_fails_honestly(no_brain):
    out = no_brain / "report.md"
    with pytest.raises(SystemExit) as exc:
        run_why("core.py", root=no_brain, out=out)
    assert exc.value.code == 1
    assert not out.exists()  # no report on failure — silent partial output is worse


def test_why_mermaid_out_without_graph_fails_honestly(no_brain):
    out = no_brain / "report.md"
    with pytest.raises(SystemExit) as exc:
        run_why("core.py", root=no_brain, mermaid=True, out=out)
    assert exc.value.code == 1
    assert not out.exists()


def test_why_out_creates_missing_parent_dirs(graph_root):
    out = graph_root / "docs" / "deep" / "report.md"
    run_why("core.py", root=graph_root, mermaid=True, out=out)
    assert out.exists()


# ── p impact --out ───────────────────────────────────────────────────────────


@pytest.fixture()
def impact_root(graph_root, monkeypatch):
    """graph_root + the layered brain fields impact_analysis needs."""
    import patchi.core.memory as mem
    from patchi.cli.commands import reason_cmd
    from patchi.core.brain.reasoning import ImpactAnalysis

    analysis = ImpactAnalysis(
        changed_files=["core.py"],
        affected_layers=["core-layer"],
        impacted_layers=["api-layer", "web-layer"],
        summary="1 file(s) changed; 1 layer(s) directly affected; 2 downstream layer(s).",
    )

    class _FakeEngine:
        def __init__(self, root):
            pass

        def impact_analysis(self, files):
            return analysis

    monkeypatch.setattr(reason_cmd, "ReasoningEngine", _FakeEngine)
    monkeypatch.setattr(
        mem,
        "get_brain",
        lambda root=None, *a, **k: {"import_graph": {"nodes": ["core.py"], "edges": {}}},
    )
    return graph_root


def test_impact_out_writes_markdown_report(impact_root):
    out = impact_root / "impact.md"
    run_impact(["core.py"], root=impact_root, out=out)
    text = out.read_text(encoding="utf-8")
    assert "# Impact analysis" in text
    assert "## Directly affected layers" in text
    assert "`core-layer`" in text
    assert "## Blast radius (downstream dependents)" in text
    assert "`web-layer`" in text
    assert "Generated by" in text  # provenance stamp


def test_impact_out_does_not_duplicate_on_stdout(impact_root, capsys):
    out = impact_root / "impact.md"
    run_impact(["core.py"], root=impact_root, out=out)
    stdout = capsys.readouterr().out
    assert "Impact analysis" not in stdout
    assert out.name in stdout


def test_impact_out_without_files_fails_honestly(impact_root):
    out = impact_root / "impact.md"
    with pytest.raises(SystemExit) as exc:
        run_impact([], root=impact_root, out=out)
    assert exc.value.code == 1
    assert not out.exists()


def test_impact_all_out_writes_blast_table(graph_root):
    """--all --out renders the full blast-radius map as a markdown table.

    Semantics (same as the human table): Direct = immediate dependents;
    Total = transitive dependents closure (files affected by changing this
    one, excluding the file itself). For core.py: 2 direct callers, total 2.
    """
    from patchi.cli.commands import reason_cmd

    graph = reason_cmd._cached_graph(graph_root)
    out = graph_root / "blast.md"
    reason_cmd._write_out(out, reason_cmd._radii_markdown(reason_cmd._blast_radii(graph)))
    text = out.read_text(encoding="utf-8")
    assert "# Blast radius map" in text
    assert "| File | Direct | Total | Risk |" in text
    assert "| `core.py` | 2 | 2 | MED |" in text
    assert "| `helper.py` | 1 | 3 | MED |" in text  # core + both callers transitively
    assert "| `caller_a.py` | — | — | LOW |" in text  # nothing depends on it


def test_impact_out_and_json_are_rejected(impact_root):
    out = impact_root / "impact.json.md"
    with pytest.raises(SystemExit) as exc:
        run_impact(["core.py"], json_output=True, root=impact_root, out=out)
    assert exc.value.code == 2
    assert not out.exists()


# ── provenance stamp ────────────────────────────────────────────────────────


def test_stamp_mentions_the_invoking_command(graph_root):
    from patchi.cli.commands.reason_cmd import _stamp

    stamp = _stamp()
    # On the real CLI sys.argv[0] is the patchi entrypoint; under pytest it's
    # pytest's — either way the stamp must carry the UTC timestamp shape.
    assert "Generated by" in stamp
    assert " UTC" in stamp
