"""Linking audit (Part 3 §1): every registered agent → CLI reachability.

Regenerates docs/LINKING_AUDIT.md. Run: python tools/gates/linking_audit.py
Add ``--check`` to exit 1 when docs/LINKING_AUDIT.md is stale relative to
the registry (CI mode — regenerates into a temp buffer and compares).
"Registered" is not "reachable" — an agent counts as CLI-reachable only if
its group is dispatched by a command runnable today (Governor phases via
`p scan`, TEST via `p test`, FIX via `p fix`) or it is referenced by name
in patchi/cli/commands/.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO))

# Groups dispatched by everyday CLI commands (Governor phases via `p scan`,
# `p test` unit path, `p fix` apply path).
DISPATCHED_GROUPS = {"scanner", "security", "test", "fix"}

TOOL_TOKENS = [
    "bandit",
    "semgrep",
    "codeql",
    "pyre",
    "safety",
    "pip-audit",
    "gitleaks",
    "osv-scanner",
    "httpx",
    "nuclei",
    "sqlmap",
    "dalfox",
    "ffuf",
    "zap",
    "shannon",
    "git",
    "node",
    "npm",
    "ollama",
    "playwright",
    "universalmutator",
    "cargo",
    "syft",
    "cdxgen",
    "trivy",
    "grype",
    "eslint",
]


def _read(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def build_report() -> tuple[str, int, int]:
    """Render the audit as text; return (markdown, agent_count, orphan_count)."""
    from patchi.core.agents.base import discover_agent_modules, list_agents

    discover_agent_modules()
    agents = sorted(list_agents(), key=lambda a: (str(getattr(a, "group", "")), a.name))

    cli_files = list((REPO / "patchi" / "cli").rglob("*.py"))
    cli_text = "\n".join(_read(f) for f in cli_files)
    web_files = list((REPO / "patchi" / "web").rglob("*.py"))
    web_text = "\n".join(_read(f) for f in web_files)
    docs_text = _read(REPO / "README.md") + "\n" + _read(REPO / "COMMANDS.md")

    import inspect

    # Not every registered agent is a CLI feature: daemons, dispatcher
    # targets, and pipeline helpers are programmatic by design. Listing them
    # here keeps the orphan table to genuine user-facing gaps.
    KNOWN_INFRA = {
        "TriageAgent": "EventBus daemon; `p governance triage` shows stats / --start subscribes live",
        "GovernanceAgent": "policy-gate wrapper; `p governance actions`/`policy` expose the audit trail",
        "HistoryAgent": "analytics reader; `p governance history` + `p trend`",
        "BlastRadiusAgent": "fix-pipeline helper; `p governance impact <symbol>` runs the same analysis",
    }

    rows = []
    for cls in agents:
        name = cls.name
        group = str(getattr(cls, "group", "")).split(".")[-1].lower()
        try:
            src = inspect.getsource(cls)
            modfile = inspect.getfile(cls)
        except Exception:
            src, modfile = "", "?"
        in_cli = bool(re.search(r"\b" + re.escape(name) + r"\b", cli_text))
        in_web = bool(re.search(r"\b" + re.escape(name) + r"\b", web_text))
        in_docs = bool(re.search(r"\b" + re.escape(name) + r"\b", docs_text))
        group_run = group in DISPATCHED_GROUPS
        tools = sorted({t for t in TOOL_TOKENS if re.search(r"\b" + re.escape(t) + r"\b", src, re.I)})
        if group_run:
            status = "OK (group dispatch)"
        elif in_cli:
            status = "OK (named in CLI)"
        elif name in KNOWN_INFRA:
            status = f"OK (infra: {KNOWN_INFRA[name]})"
        elif in_web:
            status = "ORPHAN (web-only)"
        else:
            status = "ORPHAN (nowhere)"
        rows.append(
            {
                "name": name,
                "group": group,
                "status": status,
                "in_docs": in_docs,
                "tools": tools,
                "file": Path(modfile).relative_to(REPO).as_posix() if str(modfile).startswith(str(REPO)) else modfile,
            }
        )

    orphans = [r for r in rows if r["status"].startswith("ORPHAN")]
    all_tools = sorted({t for r in rows for t in r["tools"]})

    out = []
    out.append("# Linking Audit — agent → CLI reachability (Part 3 §1)")
    out.append("")
    out.append("PURPOSE: track every registered agent's CLI reachability; close orphans.")
    out.append("OWNS: Part 3 linking pass.")
    out.append("READ-WHEN: adding/removing an agent or CLI command.")
    out.append("KEY-FILES: tools/gates/linking_audit.py, patchi/cli/registry.py.")
    out.append(
        "INVARIANTS: regenerate via `python tools/gates/linking_audit.py`; registered ≠ reachable."
    )
    out.append("GOTCHAS: group dispatch runs through Governor phases (gated agents idle without P-Check).")
    out.append("UPDATED: autogenerated — do not hand-edit below this header.")
    out.append("")
    out.append(f"Registered agents: **{len(rows)}**. ORPHANED from CLI: **{len(orphans)}**.")
    out.append("")
    out.append("## Orphans (fix or document)")
    out.append("")
    out.append("| Agent | Group | Status | File |")
    out.append("|---|---|---|---|")
    if orphans:
        for r in orphans:
            out.append(f"| {r['name']} | {r['group']} | {r['status']} | {r['file']} |")
    else:
        out.append("| — | — | none | — |")
    out.append("")
    out.append("## Full reachability table")
    out.append("")
    out.append("| Agent | Group | Status | In docs | Tools |")
    out.append("|---|---|---|---|---|")
    for r in rows:
        out.append(
            f"| {r['name']} | {r['group']} | {r['status']} | "
            f"{'yes' if r['in_docs'] else 'no'} | {', '.join(r['tools']) or '—'} |"
        )
    out.append("")
    out.append("## External tools referenced by agents (§2 registry source)")
    out.append("")
    out.append(", ".join(f"`{t}`" for t in all_tools) or "none")
    out.append("")
    out.append("## Resolutions log (hand-maintained)")
    out.append("")
    out.append(
        "- DASTAgent: was web-only → `p scan --dast` now runs it (old DastScanner module was deleted; flag rewired)."
    )
    out.append(
        "- `p security`: did not exist → built as the security-family default (full SECURITY group + skip reasons)."
    )
    out.append(
        "- `p ready` security step: hardcoded 2-agent shortlist → full "
        "SECURITY group with ran/skipped coverage statement."
    )
    out.append("- CICDGeneratorAgent: had no CLI entry → `p dev ci` runs it.")
    out.append(
        "- GUARD surface: `p governance` (actions/policy/history/verify/impact/"
        "triage/generate) built — action-log reader, history analytics, blast-"
        "radius counter, triage daemon, and CI templates are user-reachable now. "
        "Latent crashes fixed in the same pass: EWMAMeter.current_value missing, "
        "check_silence referencing nonexistent self._ewma, DetectionPipeline "
        "building Events with a nonexistent schema (Sigma stage silently disabled)."
    )
    out.append(
        "- GUARD infra (Triage/Governance/History/BlastRadius): programmatic "
        "by design (daemon/dispatcher/reader/helper) — OK (infra), not orphans."
    )
    out.append("- `p scan --dast` imported deleted `dast_scanner` (always errored) → rewired, see above.")
    out.append("")
    return "\n".join(out), len(rows), len(orphans)


def main() -> int:
    check = "--check" in sys.argv[1:]
    text, n_agents, n_orphans = build_report()
    dest = REPO / "docs" / "LINKING_AUDIT.md"

    if check:
        # CI mode: stale doc or a *new* orphan both fail the gate. Existing
        # orphans are tracked state (resolutions log); a regression is a
        # change in the full rendered text — hand-edits included.
        current = dest.read_text(encoding="utf-8") if dest.exists() else ""
        if current != text:
            print("LINKING AUDIT STALE — regenerate:", file=sys.stderr)
            print("  python tools/gates/linking_audit.py", file=sys.stderr)
            print(f"  (on disk: {len(current.splitlines())} lines; fresh: {len(text.splitlines())})", file=sys.stderr)
            return 1
        print(f"linking audit up to date (agents={n_agents}, orphans={n_orphans})")
        return 0

    dest.write_text(text, encoding="utf-8")
    print(f"agents={n_agents} orphans={n_orphans} -> {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
