"""
Pre-Commit Hook Generator — produces a POSIX sh pre-commit hook.

The generated hook runs:
  1. ruff check (fast lint gate)
  2. p scan --changed --quiet (on-demand security scan of changed files)

Both steps are non-blocking warnings by default; pass --strict to fail
the commit on violations.
"""

from __future__ import annotations

import logging
from pathlib import Path

_log = logging.getLogger("patchi.security.precommit_hook")

# ── Hook Script Template ─────────────────────────────────────────────────────


def generate_hook(
    strict: bool = False,
    with_tests: bool = False,
    with_scan: bool = True,
) -> str:
    """Generate a pre-commit hook script.

    Args:
        strict: If True, failures block the commit (exit 1).
        with_tests: If True, include pytest gate after ruff.
        with_scan: If True, include p scan --changed gate.

    Returns:
        POSIX sh script text.
    """
    lines = [
        "#!/bin/sh",
        "# Patchi pre-commit hook — generated by `p dev hook`",
        "#",
        "# Gates:",
        "#   1. ruff check (lint)",
    ]

    if with_tests:
        lines.append("#   2. pytest (tests)")
    if with_scan:
        lines.append("#   " + str(3 if with_tests else 2) + ". p scan --changed (security)")

    # NOTE: no `set -e` — each step checks $? manually so warnings
    # are non-blocking when STRICT=0.
    lines.append("STRICT=" + ("1" if strict else "0"))
    lines.append("FAIL=0")
    lines.append("")
    lines.append('echo "🔍 Patchi pre-commit hook…"')
    lines.append("")

    # Step 1: Ruff
    lines.extend(
        [
            "# ── Step 1: Ruff lint ──────────────────────────────────────────────",
            'echo "  [1/3] ruff check…"',
            "ruff check patchi/ --select E,F,W --ignore E501 --quiet 2>/dev/null",
            "if [ $? -ne 0 ]; then",
            '  echo "  ⚠️  ruff found issues (non-blocking)"',
            '  if [ "$STRICT" = "1" ]; then',
            '    echo "  ❌ Commit blocked: fix ruff errors first"',
            "    exit 1",
            "  fi",
            "  FAIL=1",
            "else",
            '  echo "  ✅ ruff clean"',
            "fi",
            "",
        ]
    )

    # Step 2: Tests (optional)
    if with_tests:
        lines.extend(
            [
                "# ── Step 2: Pytest ───────────────────────────────────────────────",
                'echo "  [2/3] pytest…"',
                "PATCHI_OFFLINE=1 python -m pytest tests/ -x -q --timeout=30 --tb=no 2>/dev/null",
                "if [ $? -ne 0 ]; then",
                '  echo "  ⚠️  pytest failed (non-blocking)"',
                '  if [ "$STRICT" = "1" ]; then',
            ]
        )
        if with_scan:
            lines.append('    echo "  ❌ Commit blocked: fix failing tests first"')
        else:
            lines.append('    echo "  ❌ Commit blocked: fix failing tests first"')
        lines.extend(
            [
                "    exit 1",
                "  fi",
                "  FAIL=1",
                "else",
                '  echo "  ✅ tests pass"',
                "fi",
                "",
            ]
        )

    # Step 3: Scan --changed (optional)
    if with_scan:
        step_num = "3" if with_tests else "2"
        total = "3" if with_tests else "2"
        lines.extend(
            [
                f"# ── Step {step_num}: On-demand security scan ──────────────────────────",
                f'echo "  [{step_num}/{total}] p scan --changed…"',
                "python -m patchi.cli.main scan --changed --quiet &",
                "SCAN_PID=$!",
                "for i in 1 2 3 4 5 6; do sleep 10; kill -0 $SCAN_PID 2>/dev/null || break; done",
                "kill $SCAN_PID 2>/dev/null && echo '  (scan timed out — results in next commit)' || true",
                "",
            ]
        )

    # Summary
    lines.extend(
        [
            "# ── Summary ────────────────────────────────────────────────────────",
            'if [ "$FAIL" = "1" ]; then',
            '  echo "⚠️  Commit succeeded with warnings. Run "p dev check" for full gate."',
            "else",
            '  echo "✅ All gates passed."',
            "fi",
            "",
            "exit 0",
        ]
    )

    return "\n".join(lines) + "\n"


def install_hook(
    root: Path,
    strict: bool = False,
    with_tests: bool = False,
    with_scan: bool = True,
) -> Path:
    """Generate and install the pre-commit hook.

    Returns the path to the installed hook.
    """
    git_dir = root / ".git"
    if not git_dir.exists():
        raise FileNotFoundError(f"Not a git repository: {root}")

    hook_path = git_dir / "hooks" / "pre-commit"
    hook_path.parent.mkdir(parents=True, exist_ok=True)

    script = generate_hook(strict=strict, with_tests=with_tests, with_scan=with_scan)
    hook_path.write_text(script, encoding="utf-8")

    try:
        hook_path.chmod(0o755)
    except OSError:
        pass  # Windows

    _log.info("Installed pre-commit hook at %s", hook_path)
    return hook_path


def read_hook_status(root: Path) -> dict:
    """Check what the installed pre-commit hook does."""
    hook_path = root / ".git" / "hooks" / "pre-commit"
    if not hook_path.is_file():
        return {"installed": False}

    content = hook_path.read_text(encoding="utf-8", errors="replace")
    return {
        "installed": True,
        "path": str(hook_path),
        "has_ruff": "ruff check" in content,
        "has_pytest": "pytest" in content,
        "has_scan": "scan --changed" in content or "scan --quiet" in content,
        "strict": "STRICT=1" in content,
    }
