"""
Pre-Commit Hook Generator - produces a POSIX sh pre-commit hook.

The generated hook runs:
  1. ruff check (fast lint gate)
  2. p scan --changed --quiet (on-demand security scan of changed files)

Both steps are non-blocking warnings by default; pass --strict to fail
the commit on violations.
"""

from __future__ import annotations

import logging
from pathlib import Path

_log = logging.getLogger("patchi.security.precommit_hook")

# -- Hook Script Template -----------------------------------------------------


def generate_hook(
    strict: bool = False,
    with_tests: bool = False,
    with_scan: bool = True,
    auto_fix: bool = False,
) -> str:
    """Generate a pre-commit hook script.

    Args:
        strict: If True, failures block the commit (exit 1).
        with_tests: If True, include pytest gate after ruff.
        with_scan: If True, include p scan --changed gate.
        auto_fix: If True, run proactive auto-fix before lint.

    Returns:
        POSIX sh script text.
    """
    lines = [
        "#!/bin/sh",
        "# Patchi pre-commit hook - generated by `p dev hook`",
        "#",
        "# Gates:",
    ]

    step_num = 1
    if auto_fix:
        lines.append(f"#   {step_num}. proactive auto-fix (charter)")
        step_num += 1
    lines.append(f"#   {step_num}. ruff check (lint)")
    if with_tests:
        step_num += 1
        lines.append(f"#   {step_num}. pytest (tests)")
    if with_scan:
        step_num += 1
        lines.append(f"#   {step_num}. p scan --changed (security)")

    # NOTE: no `set -e` - each step checks $? manually so warnings
    # are non-blocking when STRICT=0.
    lines.append("STRICT=" + ("1" if strict else "0"))
    lines.append("FAIL=0")
    lines.append("AUTO_FIX=" + ("1" if auto_fix else "0"))
    lines.append("")
    lines.append('echo "=== Patchi pre-commit hook ==="')
    lines.append("")

    total = step_num
    current_step = 0

    # Step: Auto-fix (optional)
    if auto_fix:
        current_step += 1
        lines.extend(
            [
                f"# -- Step {current_step}/{total}: Proactive auto-fix ---------------------",
                f'echo "  [{current_step}/{total}] proactive auto-fix..."',
                'python -c "from patchi.core.security.auto_fix_proactive import proactive_fix_path; \
import sys, pathlib; \
files = [pathlib.Path(f) for f in sys.argv[1:]]; \
result = proactive_fix_path(pathlib.Path.cwd(), files[0], apply=True) if files else None; \
print(f\'  auto-fixed: {len(result)} changes\' if result else \"  no changes needed\")" $GIT_PARAMS 2>/dev/null',
                'if [ $? -ne 0 ]; then',
                '  echo "  [WARN] auto-fix skipped (non-blocking)"',
                'else',
                '  echo "  [OK] auto-fix complete"',
                'fi',
                '',
            ]
        )

    # Step: Ruff
    current_step += 1
    lines.extend(
        [
            f"# -- Step {current_step}/{total}: Ruff lint ----------------------------------------------",
            f'echo "  [{current_step}/{total}] ruff check..."',
            "ruff check patchi/ --select E,F,W --ignore E501 --quiet 2>/dev/null",
            "if [ $? -ne 0 ]; then",
            '  echo "  [WARN] ruff found issues (non-blocking)"',
            '  if [ "$STRICT" = "1" ]; then',
            '    echo "  [BLOCKED] Commit blocked: fix ruff errors first"',
            "    exit 1",
            "  fi",
            "  FAIL=1",
            "else",
            '  echo "  [OK] ruff clean"',
            "fi",
            "",
        ]
    )

    # Step 2: Tests (optional)
    if with_tests:
        lines.extend(
            [
                f"# -- Step {current_step}/{total}: Pytest -----------------------------------------------",
                f'echo "  [{current_step}/{total}] pytest..."',
                "PATCHI_OFFLINE=1 python -m pytest tests/ -x -q --timeout=30 --tb=no 2>/dev/null",
                "if [ $? -ne 0 ]; then",
                '  echo "  [WARN] pytest failed (non-blocking)"',
                '  if [ "$STRICT" = "1" ]; then',
            ]
        )
        if with_scan:
            lines.append('    echo "  [BLOCKED] Commit blocked: fix failing tests first"')
        else:
            lines.append('    echo "  [BLOCKED] Commit blocked: fix failing tests first"')
        lines.extend(
            [
                "    exit 1",
                "  fi",
                "  FAIL=1",
                "else",
                '  echo "  [OK] tests pass"',
                "fi",
                "",
            ]
        )

    # Step: Scan --changed (optional)
    if with_scan:
        current_step += 1
        lines.extend(
            [
                f"# -- Step {current_step}/{total}: On-demand security scan --------------------------",
                f'echo "  [{current_step}/{total}] p scan --changed..."',
                "python -m patchi.cli.main scan --changed --quiet &",
                "SCAN_PID=$!",
                "for i in 1 2 3 4 5 6; do sleep 10; kill -0 $SCAN_PID 2>/dev/null || break; done",
                "kill $SCAN_PID 2>/dev/null && echo '  (scan timed out - results in next commit)' || true",
                "",
            ]
        )

    # Summary
    lines.extend(
        [
            "# -- Summary --------------------------------------------------------",
            'if [ "$FAIL" = "1" ]; then',
            '  echo "[WARN] Commit succeeded with warnings. Run "p dev check" for full gate."',
            "else",
            '  echo "[OK] All gates passed."',
            "fi",
            "",
            "exit 0",
        ]
    )

    return "\n".join(lines) + "\n"


def install_hook(
    root: Path,
    strict: bool = False,
    with_tests: bool = False,
    with_scan: bool = True,
    auto_fix: bool = False,
) -> Path:
    """Generate and install the pre-commit hook.

    Returns the path to the installed hook.
    """
    git_dir = root / ".git"
    if not git_dir.exists():
        raise FileNotFoundError(f"Not a git repository: {root}")

    hook_path = git_dir / "hooks" / "pre-commit"
    hook_path.parent.mkdir(parents=True, exist_ok=True)

    script = generate_hook(strict=strict, with_tests=with_tests, with_scan=with_scan, auto_fix=auto_fix)
    hook_path.write_text(script, encoding="utf-8")

    try:
        hook_path.chmod(0o755)
    except OSError:
        pass  # Windows

    _log.info("Installed pre-commit hook at %s", hook_path)
    return hook_path


def read_hook_status(root: Path) -> dict:
    """Check what the installed pre-commit hook does."""
    hook_path = root / ".git" / "hooks" / "pre-commit"
    if not hook_path.is_file():
        return {"installed": False}

    content = hook_path.read_text(encoding="utf-8", errors="replace")
    return {
        "installed": True,
        "path": str(hook_path),
        "has_ruff": "ruff check" in content,
        "has_pytest": "pytest" in content,
        "has_scan": "scan --changed" in content or "scan --quiet" in content,
        "strict": "STRICT=1" in content,
        "auto_fix": "AUTO_FIX=1" in content,
    }
