"""Security-taxonomy health: is the shipped taxonomy complete and parseable?

The scanner's domain matching, fix playbooks, and activation signals all come
from ``patchi/core/security/domains/*.yaml`` + ``fix-playbooks/*.playbook.yaml``
(regenerated by ``tools/taxonomy/generate_domains.py``). If files go missing
or get corrupted — partial install, bad merge, manual cleanup — the loader
silently skips them and **scans silently narrow**: fewer domains match, fewer
findings, fewer fixes, no error anywhere.

``check_taxonomy_health`` compares what is on disk against the expected set
below and reports precise missing/extra/unparsable names. ``p doctor``
surfaces the verdict so the narrowing is caught before it costs a scan.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

_log = logging.getLogger("patchi.security.taxonomy_health")

# The generator (tools/taxonomy/generate_domains.py) is the source of truth.
# tests/test_taxonomy_parity.py asserts EXPECTED_DOMAIN_COUNT and
# _EXPECTED_IDS equal the generator's DOMAINS table, so this constant and the
# generator cannot drift apart silently — update both (or just regenerate the
# constant from the generator) when the taxonomy changes.
EXPECTED_DOMAIN_COUNT = 800

_EXPECTED_IDS = frozenset(
    """
airflow-dag-security
angular-client-side-navigate
angular-prod-mode
angular-template-injection
angular-xss-dom-sanitizer
ansible-vault-security
api-content-negotiation
api-error-format
api-hateoas-leak
api-idempotency
api-pagination-security
api-rate-limiting
api-versioning-security
astro-islands-security
asvs-v1-verification
asvs-v10-malicious-code
asvs-v11-business-logic
asvs-v12-files-resources
asvs-v13-api
asvs-v14-config
asvs-v15-mobile
asvs-v16-iot
asvs-v2-authentication
asvs-v3-session
asvs-v4-access-control
asvs-v5-validation
asvs-v6-crypto
asvs-v7-error-handling
asvs-v8-data-protection
asvs-v9-communication
bigquery-authorized-datasets
blogic-amount-tampering
blogic-insufficient-validation
blogic-logic-bomb
blogic-price-manipulation
blogic-privilege-escalation
blogic-race-condition
blogic-resource-exhaustion
blogic-state-confusion
blogic-time-of-check
blogic-workflow-bypass
c-cpp-buffer-overflow
c-cpp-double-free
c-cpp-format-string
c-cpp-integer-overflow
c-cpp-memory-leak
c-cpp-uninitialized-memory
cicd-artifact-tampering
cicd-cache-poisoning
cicd-credential-leak
cicd-dependency-confusion
cicd-insufficient-isolation
cicd-pipeline-injection
cicd-privilege-escalation
cicd-secret-exposure
cicd-unsafe-checkout
cicd-workflow-injection
cis-amazon-linux
cis-android
cis-apache
cis-aws
cis-azure
cis-browsers
cis-centos-server
cis-consul
cis-debian
cis-docker
cis-drupal
cis-elasticsearch
cis-fedora
cis-gcp
cis-grafana
cis-haproxy
cis-iis
cis-ios
cis-istio
cis-kafka
cis-kubernetes
cis-macos
cis-mongodb
cis-mysql
cis-nginx
cis-oracle-db
cis-postgresql
cis-prometheus
cis-rabbitmq
cis-redis
cis-sql-server
cis-ssh
cis-suse
cis-terraform
cis-tomcat
cis-ubuntu-server
cis-vault
cis-vmware
cis-windows-server
cis-wordpress
cloud-aws-api-gateway
cloud-aws-cloudtrail
cloud-aws-ec2-public
cloud-aws-ecs
cloud-aws-iam-overpriv
cloud-aws-kms
cloud-aws-lambda-env
cloud-aws-rds-public
cloud-aws-s3-public
cloud-aws-sqs
cloud-azure-devops
cloud-azure-functions
cloud-azure-iam
cloud-azure-keyvault
cloud-azure-sql
cloud-azure-storage
cloud-gcp-bigquery
cloud-gcp-compute
cloud-gcp-functions
cloud-gcp-gcs
cloud-gcp-gke
cloud-gcp-iam
cloud-gcp-secrets-manager
cloudformation-security
config-dotenv-exposure
config-ini-secrets
config-json-secrets
config-spring-boot
config-toml-secrets
config-yaml-secrets
container-escape
container-healthcheck
container-image-vulnerabilities
container-log-driver
container-network-exposure
container-privileged-mode
container-read-only-fs
container-registry-security
container-resource-limits
container-root-user
container-secret-mount
crossplane-security
crypto-certificate-validation
crypto-deprecated-algorithms
crypto-ecb-mode
crypto-hardcoded-key
crypto-hmac-validation
crypto-iv-reuse
crypto-key-derivation
crypto-key-length
crypto-padding-oracle
crypto-rsa-padding
crypto-seed-entropy
crypto-timing-attack
crypto-weak-cipher
crypto-weak-hashing
crypto-weak-random
cwe-119-buffer-overflow
cwe-125-out-of-bounds-read
cwe-190-overflow
cwe-20-input-validation
cwe-200-information-exposure
cwe-209-information-through-error
cwe-22-path-traversal
cwe-269-improper-privilege
cwe-284-improper-access-control
cwe-287-improper-auth
cwe-306-missing-auth
cwe-310-cryptographic-issues
cwe-311-missing-encryption
cwe-319-cleartext-transmission
cwe-327-broken-crypto
cwe-330-use-of-insufficient-random
cwe-338-cryptographic-prng
cwe-347-verification-bypass
cwe-352-csrf
cwe-353-missing-integrity
cwe-362-race-condition
cwe-367-time-of-check-time-of-use
cwe-377-insecure-temp-file
cwe-378-creation-temp-file-with-privileged
cwe-384-session-fixation
cwe-390-error-detection
cwe-400-uncontrolled-resource
cwe-401-missing-release-of-memory
cwe-404-improper-resource-shutdown
cwe-416-use-after-free
cwe-425-direct-request-forbidden
cwe-434-unrestricted-file
cwe-434-unrestricted-upload
cwe-444-integration-multiple-representations
cwe-451-visual-misrepresentation
cwe-456-missing-initialization
cwe-460-improper-cleanup
cwe-472-external-control
cwe-476-null-pointer
cwe-497-exposure-system-info
cwe-501-trust-boundary-violation
cwe-502-deserialization
cwe-521-password-policy
cwe-522-insufficiently-protected
cwe-532-insertion-sensitive-info
cwe-541-inclusion-sensitive-info
cwe-548-exposure-information
cwe-550-server-generated-error
cwe-561-no-automation
cwe-601-open-redirect
cwe-610-exposure-redirect
cwe-611-improper-xml
cwe-643-improper-neutralization-xpath
cwe-650-trust-HTTP-methods
cwe-652-improper-neutralization-data-within-code-generation
cwe-668-exposure-resource
cwe-674-uncontrolled-recursion
cwe-693-protection-mechanism
cwe-704-incorrect-type-conversion
cwe-732-incorrect-permission
cwe-733-compilation-code-injection
cwe-77-improper-neutralization
cwe-770-allocation-without-limits
cwe-775-missing-release-descriptor
cwe-78-os-injection
cwe-787-out-of-bounds
cwe-79-xss
cwe-798-hardcoded-credentials
cwe-799-improper-control-identifier
cwe-807-improper-neutralization-user
cwe-829-inclusion-functionality
cwe-833-deadlock
cwe-838-improper-encoding
cwe-862-authorization
cwe-863-incorrect-auth
cwe-89-sqli
cwe-915-improper-neutralization-mass-assignment
cwe-918-ssrf
cwe-939-improper-authorization-handler
cwe-94-code-injection
database-audit-logging
database-backup-security
database-connection-pool
database-credential-exposure
database-data-masking
database-encryption-at-rest
database-encryption-in-transit
database-nosql-injection
database-privilege-management
database-query-optimization
database-row-level-security
database-soft-delete
database-sql-injection
database-stored-procedure
database-xss-in-output
databricks-security
dbt-model-security
devsecops-secret-scanning
django-clickjacking
django-csrf-protection
django-debug-mode
django-file-upload
django-password-hashing
django-secret-key-exposure
django-session-hijacking
django-sql-injection
django-sql-injection-raw
django-xss-template
docker-compose-security
dockerfile-security
dotnet-auth-bypass
dotnet-deserialization
dotnet-sql-injection
dotnet-viewstate-tampering
dotnet-xss-razor
edge-cache-poisoning
edge-function-injection
edge-origin-bypass
electron-context-isolation
electron-node-integration
electron-protocol-handler
electron-remote-module
electron-shell-open
email-attachment-security
email-bounce-security
email-encryption
email-link-validation
email-list-security
email-phishing
email-spoofing
email-unsubscribe-security
extension-content-script-injection
extension-message-passing
extension-remote-code
fastapi-cors-misconfig
fastapi-dependency-injection
fastapi-openapi-exposure
fastify-serialization
flask-cors-misconfiguration
flask-debug-exposure
flask-jinja2-xss
flask-session-security
flask-sql-injection
fraud-account-takeover
fraud-api-abuse
fraud-bot-detection
fraud-click-fraud
fraud-content-spam
fraud-coupon-abuse
fraud-identity-theft
fraud-payment-abuse
fraud-referral-abuse
fraud-web-scraping
game-cheat-detection
game-client-trust
game-item-duplication
game-memory-corruption
gdpr-consent
gdpr-data-breach-notification
gdpr-data-minimization
gdpr-data-protection-impact
gdpr-data-protection-officer
gdpr-data-subject-rights
gdpr-international-transfers
gdpr-lawful-processing
git-branch-protection
git-lfs-exposure
git-secrets-commit
git-signed-commits
go-command-injection
go-crypto-weak
go-path-traversal
go-race-condition
go-sql-injection
go-ssrf
go-template-injection
go-unsafe-conversion
graphql-authorization
graphql-cost-analysis
graphql-depth-limit
graphql-injection
graphql-introspection
graphql-n-plus-one
grpc-auth-bypass
grpc-insecure-connection
grpc-message-size
grpc-reflection-exposure
header-cache-control
header-cross-origin
header-csp
header-feature-policy
header-hsts
header-permissions-policy
header-referrer-policy
header-x-xss-protection
header-xcto
header-xfo
helm-chart-security
hipaa-admin-safeguards
hipaa-audit-controls
hipaa-breach-notification
hipaa-business-associate
hipaa-ephi-encryption
hipaa-ephi-transmission
hipaa-integrity-controls
hipaa-person-auth
hipaa-physical-safeguards
hipaa-technical-access-control
incident-containment
incident-detection
incident-forensics
incident-recovery
incident-response-plan
iso27001-access-control
iso27001-cryptography
iso27001-incident-management
iso27001-operations-security
iso27001-organizational
iso27001-people
iso27001-physical
iso27001-secure-development
iso27001-supplier-security
iso27001-technological
java-dep-jndi-injection
java-deserialization
java-sql-injection-jdbc
java-unsafe-reflection
java-xml-external-entity
java-xss-jsp
k8s-admission-control
k8s-api-server
k8s-dashboard-exposure
k8s-etcd-security
k8s-image-pull-policy
k8s-network-policy
k8s-pod-security
k8s-rbac
k8s-secrets-management
k8s-service-account
kafka-topic-acl
koa-middleware-skip
laravel-blade-xss
laravel-debug-mode
laravel-encryption-key
laravel-mass-assignment
laravel-sql-injection
laravel-unsafe-redirect
mitre-collection-data-staged
mitre-collection-exfil-over-c2
mitre-command-control-application-layer
mitre-command-control-encrypted-channel
mitre-credential-access-brute-force
mitre-credential-access-credential-dumping
mitre-credential-access-network-sniffing
mitre-credential-access-steal-app-tokens
mitre-defense-evasion-disable-security
mitre-defense-evasion-impair-defenses
mitre-defense-evasion-obfuscated-files
mitre-defense-evasion-signed-binary
mitre-discovery-file-directory
mitre-discovery-network-service
mitre-discovery-system-info
mitre-execution-command-scripting
mitre-execution-exploitation-client
mitre-execution-user-execution
mitre-exfiltration-over-web-service
mitre-impact-data-destruction
mitre-impact-ransomware
mitre-impact-resource-hijacking
mitre-impact-website-defacement
mitre-infiltration-command-control
mitre-initial-access-compromise-supply
mitre-initial-access-drive-by
mitre-initial-access-exploit-public
mitre-initial-access-phishing
mitre-initial-access-trusted-relationship
mitre-lateral-movement-exploitation-remote
mitre-lateral-movement-remote-services
mitre-lateral-movement-use-alternate-auth
mitre-persistence-account-manipulation
mitre-persistence-boot-autostart
mitre-persistence-create-modify-process
mitre-persistence-scheduled-task
mitre-privilege-escalation-access-token
mitre-privilege-escalation-process-injection
mitre-resource-development-accounts
mitre-resource-development-capabilities
mitre-resource-development-compromise-accounts
mitre-resource-development-obtain-capabilities
mobile-backup-security
mobile-biometric-auth
mobile-certificate-pinning
mobile-code-obfuscation
mobile-deep-link-security
mobile-insecure-storage
mobile-intent-security
mobile-jailbreak-detection
mobile-keychain-security
mobile-logging-security
mobile-pasteboard-security
mobile-permission-request
mobile-screen-capture
mobile-update-mechanism
mobile-webview-security
network-api-gateway-security
network-certificate-validation
network-cors-configuration
network-ddos-protection
network-dns-security
network-firewall-rules
network-http-headers
network-load-balancer
network-packet-filtering
network-port-exposure
network-proxy-security
network-rate-limiting
network-tls-configuration
network-vpn-security
network-waf-bypass
nextjs-api-routes-auth
nextjs-image-unoptimized
nextjs-middleware-bypass
nextjs-ssr-data-leak
nist-ac-1
nist-ac-10
nist-ac-11
nist-ac-12
nist-ac-14
nist-ac-17
nist-ac-18
nist-ac-19
nist-ac-2
nist-ac-20
nist-ac-21
nist-ac-22
nist-ac-3
nist-ac-4
nist-ac-5
nist-ac-6
nist-ac-7
nist-ac-8
nist-ac-9
nist-au-1
nist-au-10
nist-au-11
nist-au-12
nist-au-2
nist-au-3
nist-au-4
nist-au-5
nist-au-6
nist-au-8
nist-au-9
nist-cm-1
nist-cm-10
nist-cm-11
nist-cm-2
nist-cm-3
nist-cm-4
nist-cm-5
nist-cm-6
nist-cm-7
nist-cm-8
nist-cm-9
nist-csf-detect
nist-csf-govern
nist-csf-identify
nist-csf-protect
nist-csf-recover
nist-csf-respond
nist-ia-1
nist-ia-2
nist-ia-3
nist-ia-4
nist-ia-5
nist-ia-6
nist-ia-7
nist-ia-8
nist-sc-1
nist-sc-10
nist-sc-12
nist-sc-13
nist-sc-15
nist-sc-17
nist-sc-18
nist-sc-2
nist-sc-20
nist-sc-21
nist-sc-23
nist-sc-24
nist-sc-28
nist-sc-3
nist-sc-4
nist-sc-5
nist-sc-6
nist-sc-7
nist-sc-8
nist-sc-9
nist-si-1
nist-si-10
nist-si-11
nist-si-12
nist-si-15
nist-si-2
nist-si-3
nist-si-4
nist-si-5
nist-si-6
nist-si-7
nist-si-8
nodejs-callback-hell-injection
nodejs-event-emitter-injection
nodejs-express-body-parsing
nodejs-express-cors-misconfiguration
nodejs-express-error-leak
nodejs-express-middleware-missing
nodejs-express-session-security
nodejs-prototype-pollution
nodejs-regex-dos
nuxt-middleware-auth
nuxt-ssr-data-leak
owasp-a01-2025-misconfig
owasp-a01-broken-access-control
owasp-a02-2025-crypto
owasp-a02-cryptographic-failures
owasp-a03-2025-injection
owasp-a03-injection
owasp-a04-2025-access
owasp-a04-insecure-design
owasp-a05-2025-auth
owasp-a05-security-misconfiguration
owasp-a06-2025-components
owasp-a06-vulnerable-components
owasp-a07-2025-integrity
owasp-a07-auth-failures
owasp-a08-2025-ssrf
owasp-a08-integrity-failures
owasp-a09-2025-logging
owasp-a09-logging-monitoring
owasp-a10-2025-ssdlc
owasp-a10-ssrf
owasp-api-bOLA
owasp-api-bfla
owasp-api-broken-auth
owasp-api-broken-function-auth
owasp-api-consumption
owasp-api-improper-inventory
owasp-api-security-misconfig
owasp-api-srf
owasp-api-unrestricted-access
owasp-api-unrestricted-resource
owasp-iot-insecure-data
owasp-iot-insecure-data-transfer
owasp-iot-insecure-defaults
owasp-iot-insecure-ecosystem
owasp-iot-insecure-network
owasp-iot-insecure-privacy
owasp-iot-insecure-update
owasp-iot-insufficient-testing
owasp-iot-lack-of-hardening
owasp-iot-weakened-identity
owasp-llm-data-poisoning
owasp-llm-excessive-agency
owasp-llm-improper-output
owasp-llm-misinformation
owasp-llm-prompt-injection
owasp-llm-sensitive-info
owasp-llm-supply-chain
owasp-llm-system-prompt-leak
owasp-llm-unbounded-consumption
owasp-llm-vector-weakness
owasp-mobile-client-code-quality
owasp-mobile-code-tampering
owasp-mobile-extraneous-functionality
owasp-mobile-improper-platform
owasp-mobile-insecure-auth
owasp-mobile-insecure-authorization
owasp-mobile-insecure-data
owasp-mobile-insecure-transport
owasp-mobile-insufficient-crypto
owasp-mobile-reverse-engineering
owasp-nodejs-auth
owasp-nodejs-dependencies
owasp-nodejs-injection
owasp-nodejs-insecure-deserialization
owasp-nodejs-insufficient-logging
owasp-nodejs-missing-rate-limit
owasp-nodejs-open-redirect
owasp-nodejs-prototype-pollution
owasp-nodejs-security-misconfiguration
owasp-nodejs-xss
owasp-php-access-control
owasp-php-auth
owasp-php-config
owasp-php-crypto
owasp-php-deserialization
owasp-php-file-upload
owasp-php-injection
owasp-php-rce
owasp-php-sqli
owasp-php-xss
pci-encrypt-transmission
pci-identify-auth
pci-install-security
pci-log-monitor
pci-protect-account
pci-protect-malware
pci-restrict-access
pci-restrict-physical
pci-secure-config
pci-secure-systems
pci-support-policy
pci-test-security
php-config-expose
php-file-upload-exec
php-inclusion-local
php-inclusion-remote
php-type-juggling
php-unserialize
privacy-analytics-consent
privacy-consent-management
privacy-cookie-consent
privacy-cross-site-tracking
privacy-data-anonymization
privacy-data-breach-detection
privacy-data-collection
privacy-data-retention
privacy-fingerprinting
privacy-privacy-by-design
pulumi-secret-management
pwa-offline-storage
pwa-push-notification
pwa-service-worker-security
quantum-safe-crypto
qwik-hydration-security
rails-deserialization
rails-devise-security
rails-mass-assignment
rails-sql-injection
rails-xss-erb
react-client-side-routing
react-devtools-exposure
react-sensitive-data-storage
react-ssr-data-leak
react-state-tainting
react-uncontrolled-inputs
react-url-injection
react-xss-dangerously-set
redshift-security
remix-action-csrf
remix-loader-injection
rust-buffer-overflow
rust-dependency-confusion
rust-integer-overflow
rust-panic-dos
rust-unsafe-raw-pointer
sans-buffer-overflow
sans-command-injection
sans-cross-site-scripting
sans-crypto-failures
sans-csrf
sans-dos
sans-error-handling
sans-file-inclusion
sans-hardcoded-credentials
sans-information-leakage
sans-injection
sans-insecure-deserialization
sans-insufficient-auth
sans-insufficient-authorization
sans-insufficient-session-management
sans-misconfiguration
sans-open-redirect
sans-path-traversal
sans-race-condition
sans-sensitive-data-exposure
sans-sql-injection
sans-ssrf
sans-unvalidated-redirects
sans-use-after-free
sans-xml-external-entity
secrets-env-exposure
secrets-file-exposure
secrets-in-artifacts
secrets-in-backup
secrets-in-source
secrets-in-transit
secrets-logging-exposure
secrets-rotation
serverless-event-injection
serverless-insecure-dependencies
serverless-permission-overreach
serverless-secrets-exposure
snowflake-security
soc2-availability
soc2-common-criteria
soc2-confidentiality
soc2-privacy
soc2-processing-integrity
solidjs-reactivity-security
spark-data-exposure
spring-actuator-exposure
spring-bean-injection
spring-deserialization
spring-el-injection
spring-security-misconfig
spring-sqli-jpa
supply-chain-dependency-confusion
supply-chain-lock-file
supply-chain-malicious-package
supply-chain-postinstall
supply-chain-private-registry
supply-chain-repo-jacking
supply-chain-sig-verify
supply-chain-solarwinds
supply-chain-typosquatting
svelte-html-injection
svelte-reactive-leak
tauri-command-injection
tauri-permission-scope
terraform-module-source
terraform-provider-security
terraform-state-exposure
threat-model-abuse-case
threat-model-attack-surface
threat-model-mitigation
threat-model-risk-assessment
threat-model-stride
ts-decorator-injection
ts-strict-mode-bypass
vue-reactivity-security
vue-template-injection
vue-xss-v-bind
vue-xss-v-html
wasm-data-leakage
wasm-gc-exploitation
wasm-memory-safety
wasm-sandbox-escape
wasm-unsafe-imports
wasm-untrusted-code
web3-front-running
web3-governance-attack
web3-oracle-manipulation
web3-private-key
web3-smart-contract
zero-trust-architecture
""".split()
)


@dataclass
class TaxonomyHealth:
    """Result of a taxonomy health check (see check_taxonomy_health)."""

    domains_found: int = 0
    playbooks_found: int = 0
    missing_domains: list[str] = field(default_factory=list)
    missing_playbooks: list[str] = field(default_factory=list)
    extra_domains: list[str] = field(default_factory=list)
    extra_playbooks: list[str] = field(default_factory=list)
    unparsable: list[tuple[str, str]] = field(default_factory=list)  # (rel name, error)

    @property
    def expected(self) -> int:
        return EXPECTED_DOMAIN_COUNT

    @property
    def status(self) -> str:
        """ok | warn | error — error means scans are narrowing right now."""
        if self.missing_domains or self.missing_playbooks or self.unparsable:
            return "error"
        if self.extra_domains or self.extra_playbooks:
            return "warn"
        if self.domains_found != EXPECTED_DOMAIN_COUNT or self.playbooks_found != EXPECTED_DOMAIN_COUNT:
            return "error"
        return "ok"

    @property
    def summary(self) -> str:
        if self.status == "ok":
            return f"{self.domains_found} domains + {self.playbooks_found} playbooks — complete"
        bits = []
        if self.missing_domains or self.missing_playbooks:
            bits.append(f"{len(self.missing_domains)} domain(s) / {len(self.missing_playbooks)} playbook(s) MISSING")
        if self.unparsable:
            bits.append(f"{len(self.unparsable)} file(s) unparsable")
        if self.extra_domains or self.extra_playbooks:
            bits.append(
                f"{len(self.extra_domains) + len(self.extra_playbooks)} file(s) not in the expected set"
            )
        return (
            f"{self.domains_found}/{self.expected} domains, {self.playbooks_found}/{self.expected} playbooks — "
            + ", ".join(bits)
        )

    def detail_lines(self, limit: int = 3) -> list[str]:
        """First few concrete offenders, for the doctor table's detail rows."""
        lines = []
        for name in self.missing_domains[:limit]:
            lines.append(f"missing domain: {name}.yaml")
        for name in self.missing_playbooks[: max(0, limit - len(lines))]:
            lines.append(f"missing playbook: {name}.playbook.yaml")
        for name, err in self.unparsable[: max(0, limit - len(lines))]:
            lines.append(f"unparsable: {name} — {err}")
        for name in (self.extra_domains + self.extra_playbooks)[: max(0, limit - len(lines))]:
            lines.append(f"unexpected file: {name}")
        return lines


def _expected_names(expected_ids: frozenset, suffix: str) -> set[str]:
    return {f"{did}{suffix}" for did in expected_ids}


def _parse_yaml(path: Path) -> str:
    """Return "" if the file parses, else a short error reason."""
    try:
        import yaml

        try:
            Loader = yaml.CSafeLoader  # type: ignore[attr-defined]
        except AttributeError:
            Loader = yaml.SafeLoader
        with open(path, encoding="utf-8") as f:
            yaml.load(f, Loader=Loader)
        return ""
    except Exception as e:  # noqa: BLE001 — any parse failure counts as corrupt
        return str(e).splitlines()[0][:60] if str(e) else type(e).__name__


def check_taxonomy_health(package_root: Path | None = None) -> TaxonomyHealth:
    """Compare the on-disk taxonomy against the expected set.

    ``package_root`` is the ``patchi/`` package directory (defaults to this
    module's package). Both ``domains/`` and ``fix-playbooks/`` are checked
    for set parity and parseability. Never raises.
    """
    health = TaxonomyHealth()
    try:
        # parents[2] = the patchi/ package (security -> core -> patchi);
        # the dirs below are then <pkg>/core/security/{domains,fix-playbooks}.
        pkg = Path(package_root) if package_root else Path(__file__).resolve().parents[2]
        for subdir, suffix, missing_attr, extra_attr, found_attr in (
            ("domains", ".yaml", "missing_domains", "extra_domains", "domains_found"),
            ("fix-playbooks", ".playbook.yaml", "missing_playbooks", "extra_playbooks", "playbooks_found"),
        ):
            d = pkg / "core" / "security" / subdir
            expected = _expected_names(_EXPECTED_IDS, suffix)
            if not d.is_dir():
                setattr(health, missing_attr, sorted(expected)[:10])
                continue
            on_disk = {p.name for p in d.glob(f"*{suffix}")}
            setattr(health, found_attr, len(on_disk))
            # missing_* hold bare domain IDs (symmetric across domains and
            # playbooks, easy to diff); extra_* hold on-disk filenames.
            missing_ids = sorted(
                name[: -len(suffix)] for name in expected - on_disk
            )
            setattr(health, missing_attr, missing_ids)
            setattr(health, extra_attr, sorted(on_disk - expected))
            if missing_attr == "missing_domains":
                # Parse-validate every file: a truncated/corrupt file that is
                # still present would pass a count check but be silently
                # skipped by DomainLoader.
                for path in sorted(d.glob(f"*{suffix}")):
                    err = _parse_yaml(path)
                    if err:
                        health.unparsable.append((path.name, err))
            elif not health.unparsable:
                for path in sorted(d.glob(f"*{suffix}")):
                    if path.name in getattr(health, extra_attr):
                        continue
                    err = _parse_yaml(path)
                    if err:
                        health.unparsable.append((path.name, err))
    except Exception as e:  # noqa: BLE001 — doctor must never crash on this check
        _log.warning("check_taxonomy_health failed: %s", e)
        health.unparsable.append(("taxonomy check", str(e)[:60]))
    return health
